# Generated by Django 4.2.15 on 2024-08-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_orientation',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
