# Generated by Django 4.2.15 on 2024-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='orientation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
